service: aws-node-alexa-skill

custom:
  env: ${file(serverless-config/environment.yml)}

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  movieTitles:
    handler: index.handler
    events:
      - alexaSkill
        skillId: ${self:custom.SKILL_ID}
        enabled: true